# Generated by Django 4.0.6 on 2022-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
